apiVersion:  {{ default "apps/v1" .Values.deploymentApiVersion }}
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    sandboxId: "{{ .Values.sandboxId }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      sandboxId: "{{ .Values.sandboxId }}"
    matchExpressions:
      - {key: activityArn, operator: DoesNotExist}
  template:
    {{ template "pipeline.pod-template" . }}